### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by PeterEdens** [liaogang/iDLNA#2]
ld: library not found for -lCDAlbumView
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liaogang** [comment]
请移步到DLNASample这个工程,我会重新开启这个工程

**Comment by PeterEdens** [comment]
Thanks, I cloned the DLNASample source but I get an error with pod update:

[!] Unable to add a source with url `https://git.coding.net/hging/Specs.git` named `coding-hging-specs`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

**Comment by liaogang** [comment]
注释掉那行就可以了.
整个工程只有一个pod依赖
pod 'AsyncDisplayKit'

**Comment by PeterEdens** [comment]
It also fails for PINRemoteImage because it requires a username and password for the git repo.
